version: '3'

services:
   api:
    build: ./
    image: api
    command: uvicorn app.api:app --host 0.0.0.0 --port 8000
    ports:
      - 8000:8000
    networks:
      - test_network

networks:
   test_network: 
      driver: bridge