version: "3.8"

services:
  api-cuda:
    build:
      context: .
      dockerfile: Dockerfile.cuda
    container_name: market-maven-be-cuda
    ports:
      - "8000:8000"
    volumes:
      - ./config:/app/config
      - ./artifacts:/app/artifacts
      - ./.env:/app/.env
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
