version: "3.8"

services:
  miniconda:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    networks:
      - market-maven
    dns:
      - 8.8.8.8
      - 8.8.4.4

networks:
  market-maven:

